{
 "title": "Dashboard de métricas relevantes",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Requisições por segundo - Última hora",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(promhttp_metric_handler_requests_total[5m])"
    }
   ]
  },
  {
   "title": "URLs mais lentas - Última hora",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk(10, sum by (uri) (prometheus_http_request_duration_seconds_sum/prometheus_http_request_duration_seconds_count))"
    }
   ]
  },
  {
   "title": "Requests mais acessadas - Última hora",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "topk(10, sum by (uri) (rate(prometheus_http_request_duration_seconds_sum[1h])))"
    }
   ]
  },
  {
   "title": "Tempo médio de resposta - Últimas 24 horas",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(prometheus_http_request_duration_seconds_sum/prometheus_http_request_duration_seconds_count)"
    }
   ]
  },
  {
   "title": "Requests com status code 400 ou 500 - Última Hora",
   "type": "graph",
   "description": "Mostrando as requests que retornaram erro 400 ou 500.",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 18 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk(10, \n    sum by(uri) (rate(prometheus_http_request_duration_seconds_sum{status=~\"4..|5..\"}[10m]))\n)"
    }
   ]
  },
  {
   "title": "URLs mais lentas - Última hora",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 30 },
   "targets": [
    {
     "expr": "topk(10, sum by (uri) (rate(prometheus_http_request_duration_seconds_sum[1h])))"
    }
   ]
  }
 ]
}