--- 
global: 
  evaluation_interval: 5s
  scrape_interval: 5s
scrape_configs: 
  - 
    job_name: mysql
    static_configs: 
      - 
        labels: 
          alias: db1
        targets: 
          - "192.168.56.107:9104"
