version: '3.5'

services:
  generator:
    image: labbsr0x/metrics-generator-tabajara
    build: .
    environment:
      - COMPONENT_NAME=testserver
      - COMPONENT_VERSION=1.0.0
    ports:
      - 3000:3000

  prometheus:
    build: .
    ports:
      - 9090:9090
    environment:
      - SCRAPE_INTERVAL=15s
      - SCRAPE_TIMEOUT=10s
      - STATIC_SCRAPE_TARGETS=generator:3000
  