scrape_configs:
  - job_name: 'federate_federate'
    scrape_interval: 15s

    honor_labels: true
    metrics_path: '/federate'

    params:
      'match[]':
        - '{job="prometheus"}'
        - '{__name__=~"job:.*"}'

    static_configs:
      - targets:
        - 'prometheus_federation:9090'
    
rule_files:
  - 'new_rules.yml'