scrape_configs:
  - job_name: 'federation'
    scrape_interval: 15s

    honor_labels: true
    metrics_path: '/federate'

    params:
      'match[]':
        - '{job="federate_n1"}'

    static_configs:
      - targets:
        - 'prometheus:9090'

rule_files:
  - 'prometheus.rules.yml'