scrape_configs:
  - job_name: 'generator'
    scrape_interval: 15s

    honor_labels: true
    metrics_path: '/metrics'

    static_configs:
      - targets:
        - 'generator:3000'

rule_files:
  - 'prometheus.rules.yml'